travis:
  secure:
    BINSTAR_TOKEN: LfXp24+HaUnRA/D68Peq9jWcUXL06SpRph4swl5ctFdw5bHfRyEyufXc7rOlgJXUXu3GC9PnkXWPqxRdpgYDJjfNDX33Tl5q1iXcYRw7QVYphKT3cyzRNvkABkbzltMDJP7zMx+0wEfzFhjm4gCia/Lbv2KEm6pzCCksspEx0tnktO9CIa5L/aOznUgFkRrKjdeSuNnEhh0IaxakNEKlQz+mOi9MsJJ7mOuUMK6H5kNy8T+qVJXepOHwRTOiB7jwB2avTS7LeXXR2luLREcnFSVN3ecYEsqSiTYi1CkaK1VgQVLXkmKB8B9J/oFlI7oH21FaI0Hz3TRJDNpQvUzQvtQAQPDJNGhm8ipTiAOlH+kEKD5QDgC+1WQ+1k8Ru/99p7aIqS6mRHdoT9xO5xUreUQokwFNTCzMwDn7reYincLn31/EsYXVcGg9rkwTSNCa4LIAF9nkgcFOYRxgSt+KNSQgvlb1piZcZcLs+HlhEHnkRLjZCmC053mzatYyvKi2FeXZTKIKn6ZeTmXH5JyT8Lj5W73sMACOeaXbuebCldzG4L/e6nZ/ZzlPHyDwxrgewGkixVkMcMAwmcN3YyFKErbWmxDr29ypfHqC895LORH2GSEdI4oY9ljiMt4VAYvriai7s6PyUWiwUDa4fDWFEP4b0CvjpNCOPhqx6AvMRWM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
