travis:
  secure:
    BINSTAR_TOKEN: E2blKJKh1su2cGVkeceRvPuidecZLNiEbFor0aSfWq6qWjwpTE9SKxaCIfqKPtBKqM8mHjj/ABomOPs5LRjAEqLhEXLyAlUCG60oI95G9fTGt4fk3tkGIiIc6PgopmMB7odLVhVukJmk+sBzX4f6sHpoEC2ntRX/KphwLyxdhOQpas6BLTfPH63woDQwv2Y0QJr6Nl0tBQp2NSL8FlqD/7vk3n6FXvH/zCCmRQe8CuEOk+B4Rb1okNDYBRzrOEOwZ4fkDSwRcV5R5KOWKvueu2uXJ+IKhw99cKXoP8VukUEXLkrSxIzYggmfpPK60zz0oWKqDslZPqXl/ypj/hPZXypKRRlH4aBB+CjVxnn/59p6cnJGSvG6VOK/wWTXI9T5IEo7+gbEYu5r8da3qqVkX2CI674eRt6gO3ZNU9gRZKQelMbWjZauNV6Iqazyu9ybE/OJxddgps6qM2wMWvMdlhxs6N+9L39PksAO294MarffP8TL9lqZo2kaRlmeR63cT4t+pANsc4vKg6w9IaGt8gnaXrl7TKBHPpdpcuk4cKj3VtT2a9i1EdgO/YM/glMu8FNWDhYpqNJhF56SFn0ACkXASVYKAek2t5ulMuTUDoCaYBzyNezIG6S2rBchLUIJyQ5Po93Q+e5jO4j3D7bZSIDmshCNu3kYoJbbLizPtuM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
